Mobile menu window
baezluise/portfolio-project pull request #11
Opened 2023-04-17 15:07 UTC by baezluise

2023-04-17 19:09 UTC, emmiiorji requested changes
Hi @baezluise, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220870678-4f45b7ed-1d79-4e6a-9338-da59224b2cbc.gif'/>
</div>

You have submitted a pair programming project without commits from other team member(s). Kindly ensure that every member of the team contributes to the project evidenced by their commits.

Also, kindly include a description for your pull request in order to know at a glance the changes implemented.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-17 21:34 UTC, GzimAsani requested changes
### Hello, @baezluise                   :wave:   
 Good job so far,  done There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with javascript modal, it works great :+1: 

 ## Required Changes 

- [ ] Check the comments below :arrow_double_down: 

 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers, and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-17 21:34 UTC, GzimAsani commented on index.html
>        <nav id="nav">
- [ ]  Please give padding to the sides of hamburger button in order to match the design better

Yours:
![image](https://user-images.githubusercontent.com/62705947/232614645-7930e172-700f-4b33-94eb-58c325642356.png)

Design:
![image](https://user-images.githubusercontent.com/62705947/232614597-278d9b26-9e61-40cc-93a7-6dca74f4329e.png)

2023-04-17 21:34 UTC, GzimAsani commented on index.html
> +        </div>
- [ ] Kindly check the paddings on the X and the content in order to match better the design


Yours:
![image](https://user-images.githubusercontent.com/62705947/232615540-1e4b4b00-d794-46f1-b492-f3827e194511.png)

Design:
![image](https://user-images.githubusercontent.com/62705947/232615273-62cec9d6-3b3b-4c96-8f9d-c1093d2d03ae.png)

2023-04-17 22:52 UTC, Ismailco approved these changes
### Hi @baezluise, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️ No linter errors
✔️ Used GitHub Flow
✔️ Work documented professionally

## Optional suggestions
- [ ] **Kindly make sure to add a description to the PR so it reflects the changes in this Branch**
- [ ] Kindly make sure to add a LICENSE to your README file instead so your project has a proper `MIT` License (you can choose any open-source license you want)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-18 11:05 UTC, baezluise commented
Mobile menu window added with js events and styled with css

2023-04-18 11:05 UTC, merged